### ISSUE TITLE
Controller Issues

### ISSUE THREAD

**Issue by Bryceless** [rjoudrey/LT-Riftless#2]
When using this patch with the latest version of the game, when it prompts me to "Press A to start", I cannot pass this part, although I have an Xbox 360 controller plugged into my PC.

**Comment by rjoudrey** [comment]
I could be wrong, but I don't think the patch is causing that issue.

**Comment by BactaBobomb** [comment]
I'm at my wit's end with this controller issue.  I am also having it.  I have tried everything.  Unplugging and replugging in, unplugging all other USB devices, uninstalling the controller, restarting the computer, making sure the controller is being treated as the first device, downloading Android emulators on the PC to try out VRidge so that the computer treats my "Android" as a headset and therefore Oculus lets me use my controller on it, TrinusVR to do the same thing, SteamVR... ugh...

I've tried everything and I can't get my dang controller to get recognized :(
